<?php

use Illuminate\Database\Seeder;

class StocksTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('stocks')->insert([
            [
                'product_id'=>1,
                'name'=>"32",
                'quantity'=>0,
            ],
            [
                'product_id'=>1,
                'name'=>"33",
                'quantity'=>10,
            ],
            [
                'product_id'=>1,
                'name'=>"34",
                'quantity'=>10,
            ],
            [
                'product_id'=>1,
                'name'=>"35",
                'quantity'=>10,
            ],
            [
                'product_id'=>1,
                'name'=>"36",
                'quantity'=>10,
            ],
            [
                'product_id'=>1,
                'name'=>"37",
                'quantity'=>10,
            ],
            [
                'product_id'=>1,
                'name'=>"38",
                'quantity'=>10,
            ],
            [
                'product_id'=>2,
                'name'=>"39",
                'quantity'=>10,
            ],
            [
                'product_id'=>2,
                'name'=>"40",
                'quantity'=>10,
            ],
            [
                'product_id'=>2,
                'name'=>"32",
                'quantity'=>0,
            ],
            [
                'product_id'=>2,
                'name'=>"33",
                'quantity'=>10,
            ],
            [
                'product_id'=>2,
                'name'=>"34",
                'quantity'=>10,
            ],
            [
                'product_id'=>2,
                'name'=>"35",
                'quantity'=>10,
            ],
            [
                'product_id'=>3,
                'name'=>"36",
                'quantity'=>10,
            ],
            [
                'product_id'=>3,
                'name'=>"37",
                'quantity'=>10,
            ],
            [
                'product_id'=>3,
                'name'=>"38",
                'quantity'=>10,
            ],
            [
                'product_id'=>3,
                'name'=>"39",
                'quantity'=>10,
            ],
            [
                'product_id'=>3,
                'name'=>"40",
                'quantity'=>10,
            ],
            [
                'product_id'=>4,
                'name'=>"32",
                'quantity'=>0,
            ],
            [
                'product_id'=>4,
                'name'=>"33",
                'quantity'=>10,
            ],
            [
                'product_id'=>4,
                'name'=>"34",
                'quantity'=>10,
            ],
            [
                'product_id'=>4,
                'name'=>"35",
                'quantity'=>10,
            ],
            [
                'product_id'=>4,
                'name'=>"36",
                'quantity'=>10,
            ],
            [
                'product_id'=>4,
                'name'=>"37",
                'quantity'=>10,
            ],
            [
                'product_id'=>4,
                'name'=>"38",
                'quantity'=>10,
            ],
            [
                'product_id'=>5,
                'name'=>"39",
                'quantity'=>10,
            ],
            [
                'product_id'=>5,
                'name'=>"40",
                'quantity'=>10,
            ],
            [
                'product_id'=>5,
                'name'=>"32",
                'quantity'=>0,
            ],
            [
                'product_id'=>5,
                'name'=>"33",
                'quantity'=>10,
            ],
            [
                'product_id'=>6,
                'name'=>"34",
                'quantity'=>10,
            ],
            [
                'product_id'=>6,
                'name'=>"35",
                'quantity'=>10,
            ],
            [
                'product_id'=>6,
                'name'=>"36",
                'quantity'=>10,
            ],
            [
                'product_id'=>6,
                'name'=>"37",
                'quantity'=>10,
            ],
            [
                'product_id'=>7,
                'name'=>"38",
                'quantity'=>10,
            ],
            [
                'product_id'=>7,
                'name'=>"39",
                'quantity'=>10,
            ],
            [
                'product_id'=>7,
                'name'=>"40",
                'quantity'=>10,
            ],
            [
                'product_id'=>7,
                'name'=>"32",
                'quantity'=>0,
            ],
            [
                'product_id'=>7,
                'name'=>"33",
                'quantity'=>10,
            ],
            [
                'product_id'=>7,
                'name'=>"34",
                'quantity'=>10,
            ],
            [
                'product_id'=>8,
                'name'=>"35",
                'quantity'=>10,
            ],
            [
                'product_id'=>8,
                'name'=>"36",
                'quantity'=>10,
            ],
            [
                'product_id'=>8,
                'name'=>"37",
                'quantity'=>10,
            ],
            [
                'product_id'=>8,
                'name'=>"38",
                'quantity'=>10,
            ],
            [
                'product_id'=>9,
                'name'=>"39",
                'quantity'=>10,
            ],
            [
                'product_id'=>9,
                'name'=>"40",
                'quantity'=>10,
            ],
            [
                'product_id'=>9,
                'name'=>"32",
                'quantity'=>0,
            ],
            [
                'product_id'=>10,
                'name'=>"33",
                'quantity'=>10,
            ],
            [
                'product_id'=>11,
                'name'=>"34",
                'quantity'=>10,
            ],
            [
                'product_id'=>12,
                'name'=>"35",
                'quantity'=>10,
            ],
            [
                'product_id'=>13,
                'name'=>"36",
                'quantity'=>10,
            ],
            [
                'product_id'=>14,
                'name'=>"37",
                'quantity'=>10,
            ],
            [
                'product_id'=>15,
                'name'=>"38",
                'quantity'=>10,
            ],
            [
                'product_id'=>16,
                'name'=>"39",
                'quantity'=>10,
            ],
            [
                'product_id'=>17,
                'name'=>"39",
                'quantity'=>10,
            ],
            [
                'product_id'=>17,
                'name'=>"40",
                'quantity'=>10,
            ],
            [
                'product_id'=>18,
                'name'=>"38",
                'quantity'=>10,
            ],
            [
                'product_id'=>18,
                'name'=>"39",
                'quantity'=>10,
            ],
            
            

        ]);
    }
}